project_id = "umrgfcppgptuawtfcnqw"

[functions.generate-screenshot]
verify_jwt = false

[functions.screenshot-webhook]
verify_jwt = false

[functions.train-ai-demo-widget]
verify_jwt = false

[functions.ghl-chat-webhook]
verify_jwt = false

